language: ruby

rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4
  - jruby-head

env:
  - SUITE=rspec spec
  - SUITE=rubocop

script: bundle exec $SUITE

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

before_install: gem update bundler
bundler_args: --without guard -j 3

sudo: false
cache: bundler
